// Generated by CoffeeScript 1.7.1
(function() {
  var Sequence, apply, cycle, expect, increment, interleave, interpose, isEven, isOdd, iterate, map, multiply, range, reduce, reductions, repeat, rest, sum, take, toArray, _ref;

  expect = require('chai').expect;

  _ref = require('fl'), Sequence = _ref.Sequence, map = _ref.map, sum = _ref.sum, multiply = _ref.multiply, isEven = _ref.isEven, isOdd = _ref.isOdd, increment = _ref.increment, rest = _ref.rest, repeat = _ref.repeat, cycle = _ref.cycle, iterate = _ref.iterate, range = _ref.range, apply = _ref.apply, reduce = _ref.reduce, reductions = _ref.reductions, interleave = _ref.interleave, interpose = _ref.interpose, take = _ref.take, toArray = _ref.toArray;

  describe("a few basics:", function() {
    it("does `rest`", function() {
      var array;
      array = toArray(rest([0, 1, 2, 3]));
      return expect(array.join(' ')).to.equal('1 2 3');
    });
    it("does `range`, `interleave`, `toArray`", function() {
      var array;
      array = toArray(interleave([0, 1, 2], range(3, 9), [9, 10, 11, 12]));
      return expect(array.join(' ')).to.equal('0 3 9 1 4 10 2 5 11');
    });
    it("does cast to `Sequence`, `cycle`, `take`", function() {
      var array;
      array = Sequence([1, 2, 3]).cycle().take(10).toArray();
      return expect(array.join(' ')).to.equal('1 2 3 1 2 3 1 2 3 1');
    });
    it("does `reduce`", function() {
      expect(Sequence().reduce(sum)).to.equal(0);
      expect(Sequence().reduce(multiply)).to.equal(1);
      expect(Sequence([42]).reduce(sum)).to.equal(42);
      return expect(Sequence([42, 58]).reduce(sum)).to.equal(100);
    });
    it("does `concat`", function() {
      var array;
      array = Sequence([4]).concat(Sequence.range(1, 4).cycle()).take(20).toArray();
      return expect(array.join(' ')).to.equal('4 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1');
    });
    it("does `partition`", function() {
      var array;
      array = Sequence.range(40).partition(3, 10).map(function(s) {
        return toArray(s).join(' ');
      }).toArray();
      expect(array.join(' ')).to.equal('0 1 2 10 11 12 20 21 22 30 31 32');
      array = Sequence.range(10).partition(4, 2).map(function(s) {
        return toArray(s).join(' ');
      }).toArray();
      expect(array.join(' ')).to.equal('0 1 2 3 2 3 4 5 4 5 6 7 6 7 8 9');
      array = Sequence.range(10).partition(6, 3, [97, 98, 99]).map(function(s) {
        return toArray(s).join(' ');
      }).toArray();
      return expect(array.join(' ')).to.equal('0 1 2 3 4 5 3 4 5 6 7 8 6 7 8 9 97 98');
    });
    return it("does `partitionBy`", function() {
      var array;
      array = Sequence.range(20).partitionBy(function(n) {
        return (Math.sqrt(n)) | 0;
      }).map(function(s) {
        return toArray(s).join(' ');
      }).toArray();
      return expect(array.join(' / ')).to.equal('0 / 1 2 3 / 4 5 6 7 8 / 9 10 11 12 13 14 15 / 16 17 18 19');
    });
  });

  describe("examples from external sources", function() {
    return it("chains [ iterate, filter, partition, map, take, reduce ]", function() {
      var result;
      result = Sequence.iterate(increment, 0).filter(isOdd).partition(2, 1).map(Sequence).map(function(s) {
        return s.reduce(multiply);
      }).take(1000).reduce(sum);
      return expect(result).to.equal(1335333000);
    });
  });

  describe("a bit of performance:", function() {
    return it("skedaddles", function() {
      var i, m, n, square, t;
      square = function(x) {
        return x * x;
      };
      n = 1000;
      m = 10000;
      i = 0;
      t = Date.now();
      while (i++ < n) {
        Sequence.range(m).map(square).toArray();
      }
      t = Date.now() - t;
      return console.log("(n = " + n + ") * (m = " + m + ") : range, map, toArray -> " + t + " ms -> " + (n * m * 1000 / t) + " elem-op/s");
    });
  });

}).call(this);
